# domain https://reliable-moxie-860fc7.netlify.app/
name: GitHub Action Demo
on:
  workflow_dispatch: #(ручной запуск джобы)
  push:
    branches: [master, develop]
    # path-ignore: # указываем файлы при пуше которых не вызываем джобы
    #   - './gitignore'
  pull_request:
    branches: [master, develop]
    types: [opened, edited, reopened]
jobs:
  init:
    strategy:
      matrix: # проверка билда на разных нодах и ОС
        node-version: [14, 16, 18.x]
        os: [ubuntu-latest, window-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3 # получили исходный код в проект
      # - name: Staring Node.js ${{ matrix.node-version }} # install node
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: ${{ matrix.node-version }}
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: install modules
        run: npm ci # ci безопаснее install (при наличии lock файла)
      - name: github object print
        run: echo "${{ toJSON(github) }}" #github - global context
  test:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - uses: actions/checkout@v3 # получили исходный код в проект
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: install modules
        run: npm ci # ci безопаснее install (при наличии lock файла)
      - name: unit test project
        run: npm run test:unit
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3 # получили исходный код в проект
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: install modules
        run: npm ci # ci безопаснее install (при наличии lock файла)
      - name: build project
        run: npm run build
      - name: build storybook project
        run: npm run build:storybook
      - name: unit test project
        run: npm run test:unit
      - name: e2e test project
        run: npm run test:e2e
      - name: lint check
        run: npm run lint
      - name: type check
        run: npm run type:check
      - name: i18next check
        run: npm run i18n:check
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3 # получили исходный код в проект
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: install modules
        run: npm ci # ci безопаснее install (при наличии lock файла)
      - name: deploy project
        run: echo "Deploy project..."


